# Exit
bind=CTRL+ALT,q,quit
bind=SUPER,q,killclient,

# Scripts
bind=SUPER+SHIFT,R,spawn,/home/chandler/.config/mango/reshell.sh
bind=SUPER+SHIFT,S,spawn,/home/chandler/.config/mango/screenshot.sh

# Terminal
bind=SUPER,Return,spawn,ghostty

# Fuzzel
#bind=SUPER,Space,spawn,fuzzel
bind=SUPER,Space,spawn,noctalia-shell ipc call launcher toggle
# Overview
bind=SUPER,0,toggleoverview

# Hot Reload
bind=SUPER,r,reload_config

# Volume
bind=none,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bind=none,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bind=none,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bind=none,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

# Monitor
bind=SUPER,bracketleft,focusmon,left
bind=SUPER,bracketright,focusmon,right

# Window Focus
# bind=SUPER,Tab,focusstack,next
bind=SUPER,Left,focusdir,left
bind=SUPER,Right,focusdir,right
bind=SUPER,Up,focusdir,up
bind=SUPER,Down,focusdir,down

# Window Swap
bind=SUPER+SHIFT,Up,exchange_client,up
bind=SUPER+SHIFT,Down,exchange_client,down
bind=SUPER+SHIFT,Left,exchange_client,left
bind=SUPER+SHIFT,Right,exchange_client,right

# Window Status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=SUPER+ALT,c,togglefloating,
bind=SUPER+ALT,a,togglemaximizescreen,
bind=SUPER+ALT,f,togglefullscreen,
#bind=ALT+SHIFT,f,togglefakefullscreen,
bind=SUPER,o,toggleoverlay,

# Scratchpad
bind=SUPER,i,minimized,
bind=SUPER+SHIFT,I,restore_minimized
bind=SUPER,s,toggle_scratchpad

# Scroller Layout
bind=ALT,e,set_proportion,1.0
bind=ALT,x,switch_proportion_preset,
# bind=SUPER,s,setlayout,scroller

# Switch Layout
bind=SUPER,n,switch_layout
bind=SUPER,comma,setlayout,tile
bind=SUPER,period,setlayout,scroller

# Tag Switch
bind=ALT,Left,viewtoleft,0
bind=ALT,Right,viewtoright,0
bind=CTRL+SUPER,Left,tagtoleft,0
bind=CTRL+SUPER,Right,tagtoright,0

bind=Ctrl,1,view,1,0
bind=Ctrl,2,view,2,0
bind=Ctrl,3,view,3,0
bind=Ctrl,4,view,4,0
bind=Ctrl,5,view,5,0
bind=Ctrl,6,view,6,0
bind=Ctrl,7,view,7,0
bind=Ctrl,8,view,8,0
bind=Ctrl,9,view,9,0

bind=Alt,1,tagsilent,1,0
bind=Alt,2,tagsilent,2,0
bind=Alt,3,tagsilent,3,0
bind=Alt,4,tagsilent,4,0
bind=Alt,5,tagsilent,5,0
bind=Alt,6,tagsilent,6,0
bind=Alt,7,tagsilent,7,0
bind=Alt,8,tagsilent,8,0
bind=Alt,9,tagsilent,9,0

# Monitor Shift
bind=ALT+SHIFT,Left,tagmon,left
bind=ALT+SHIFT,Right,tagmon,right

# Gaps
bind=ALT+SHIFT,X,incgaps,1
bind=ALT+SHIFT,Z,incgaps,-1
bind=ALT+SHIFT,R,togglegaps

# Move Window
bind=SUPER+SHIFT,Up,movewin,+0,-50
bind=SUPER+SHIFT,Down,movewin,+0,+50
bind=SUPER+SHIFT,Left,movewin,-50,+0
bind=SUPER+SHIFT,Right,movewin,+50,+0

# Resize Windows
bind=SUPER+ALT,Up,resizewin,+0,-50
bind=SUPER+ALT,Down,resizewin,+0,+50
bind=SUPER+ALT,Left,resizewin,-50,+0
bind=SUPER+ALT,Right,resizewin,+50,+0

# Mouse Button Bindings
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

# Axis Bindings
axisbind=SUPER,UP,viewtoleft_have_client
axisbind=SUPER,DOWN,viewtoright_have_client
