layerrule=animation_type_open:zoom,layer_name:rofi
layerrule=animation_type_close:fade,layer_name:rofi

# no blur slurp select layer
layerrule=noblur:1,layer_name:selection

# layerrule=noblur:0,layer_name:rofi

windowrule=isfloating:1,isoverlay:1,appid:mpv

windowrule=isfloating:1,isoverlay:1,appid:thunar

windowrule=isoverlay:1,isfloating:1,appid:Thunar,title:.*Rename.*
windowrule=isoverlay:1,isfloating:1,appid:Thunar,title:.*Properties.*
windowrule=isoverlay:1,isfloating:1,appid:Thunar,title:.*Preferences.*
windowrule=isoverlay:1,isfloating:1,appid:Thunar,title:.*Custom.*
windowrule=isoverlay:1,isfloating:1,appid:Thunar,title:.*Configure.*
