[config]

# [templates.bat]
# input_path  = '~/.config/matugen/templates/terminal/bat.theme'
# output_path = '~/.config/bat/themes/Matugen.theme'

[templates.btop]
input_path  = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

# [templates.cava]
# input_path  = "~/.config/matugen/templates/cava.ini"
# output_path = "~/.config/cava/matugen"
# post_hook = 'pkill -USR1 cava'

[templates.ghostty]
input_path  = "~/.config/matugen/templates/ghostty"
output_path = "~/.config/ghostty/themes/Matugen"
post_hook = 'pkill -SIGUSR2 ghostty'

[templates.helix]
input_path  = "~/.config/matugen/templates/helix.toml"
output_path = '~/.config/helix/themes/matugen.toml'

# [templates.mango]
# input_path = '~/.config/matugen/templates/mango.conf'
# output_path = '~/.config/mango/colors.conf'
# post_hook = 'mmsg -d reload_config' 

[templates.niri]
input_path = '~/.config/matugen/templates/niri.kdl'
output_path = '~/.config/niri/colors.kdl'
post_hook = 'niri msg action load-config-file'

[templates.obsidian]
input_path = '~/.config/matugen/templates/obsidian.css'
output_path = '~/Documents/Vault/.obsidian/snippets/matugen.css'

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell.qml'
output_path = '~/.local/state/quickshell/colors.json'

[templates.starship]
input_path = '~/.config/matugen/templates/starship.toml'
output_path = '~/.config/starship.toml'

[templates.steam]
input_path = '~/.config/matugen/templates/steam.css'
output_path = '~/.config/AdwSteamGtk/custom.css'
post_hook =  'adwaita-steam-gtk -i'

[templates.vesktop]
input_path = '~/.config/matugen/templates/midnight-discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi.toml'
output_path = '~/.config/yazi/theme.toml'

[templates.zathura]
input_path = '~/.config/matugen/templates/zathura'
output_path = '~/.config/zathura/zathurarc'

