ipc = off
preload = /home/chandler/Pictures/r2.png
preload = /home/chandler/Pictures/diner.png
wallpaper = HDMI-A-2, /home/chandler/Pictures/r2.png
wallpaper = DP-3, /home/chandler/Pictures/diner.png
