add_newline = false
format = "$all"
scan_timeout = 10

[buf]
symbol = " "

[c]
symbol = " "

[character]
error_symbol = "[✗](bold red) "
success_symbol = "[➜](bold green) "

[directory]
read_only = " 󰌾"
style = "bold italic blue"
truncate_to_repo = true

[docker_context]
style = "bold blue"
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[ocaml]
symbol = " "

[package]
symbol = "󰏗 "

[python]
style = "bold yellow"
symbol = " "

[rust]
symbol = " "

[swift]
symbol = " "

[username]
show_always = true

[zig]
symbol = " "
